### ISSUE TITLE
Build on Ruby 3.2.0

### ISSUE THREAD

**Issue by jaredmoody** [nak1114/ruby-extension-pigpio#3]
I'm having trouble installing this gem on a pi with ruby 3.2.0.

Here's a [gist of the output](https://gist.github.com/jaredmoody/4259e0b36beb2a13f087954671ab6181), and though I see some warnings, I don't see anything obvious indicating what's wrong.

Can you provide any direction?

Thank you!

**Comment by vickash** [comment]
See #6. It works, but there are still a bunch of warnings.

You can build from [my fork](https://github.com/vickash/ruby-extension-pigpio) in the meantime.

`gem build` and `gem install` seem to be enough, run on the Pi itself. I didn't run the setup script.

**Comment by daBee** [comment]
I'm running into the same on 3.2.2.  I'm not clear on the reply.

**Comment by vickash** [comment]
> I'm running into the same on 3.2.2. I'm not clear on the reply.

I made my own copy (fork) of this gem's code and fixed the problem there. I submitted a pull request (#6) to the gem maintainer so they can merge my fixes, and likely release a new version which will be available through `gem install`. Until that happens, you can use the fixed version by downloading the code from my fork, building it and manually installing it yourself.

On a Pi, in the top level directory of the source folder:
```
gem build
gem install *.gem
```

**Comment by daBee** [comment]
Eggcellent.

**Comment by vickash** [comment]
@nak1114 since you merged the changes, could we get a new version pushed to rubygems.org please?

**Comment by nak1114** [comment]
It was the first release in a long time, so it took a lot of time.
We have successfully released it to rubygems, so please give it a try!
